name: BlockRestore
author: icestar
version: 2.0
main: org.sct.BlockRestore.Main
description: 方块复原
api-version: 1.13
commands:
  blockrestore:
    description: 插件主命令
    usage: "/br"
    aliases: [BlockRestore,blockrestore,blr,br]
