name: BlockRestore
author: LovesAsuna
version: 3.0
main: org.sct.BlockRestore.BlockRestore
depend: [EasyLib]
description: 方块复原
api-version: 1.13
commands:
  blockrestore:
    description: 插件主命令
    usage: "/blockrestore"
    aliases: [blr,br]
